#order of cards is 0 to 21

list_of_major_arcana = ["The Fool", "The Magician", "The High Priestess", "The Empress", "The Emperor", "The Hierophant", "The Lovers",
                        "The Chariot", "Strength", "The Hermit", "The Wheel of Fortune", "Justice", "The Hanged Man", "Death", "Temperance",
                        "The Devil", "The Tower", "The Star", "The Moon", "The Sun", "Judgement", "The World"]

dictionary_of_lists_major_arcana_to_positive_attributes = {
    "The Fool": "beginnings, freedom, innocence, originality, adventure, idealism, spontaneity".split(', '),
    "The Magician": "willpower, desire, being resourceful,, skill, ability, concentration, manifestation".split(', '),
    "The High Priestess": "unconscious, intuition, mystery, spirituality, higher power, inner voice".split(', '),
    "The Empress": "divine feminine, sensuality, fertility, nurturing, creativity, beauty, abundance, nature".split(', '),
    "The Emperor": "stability, structure, protection, authority, control, practicality, focus, discipline".split(', '),
    "The Hierophant": "tradition, social groups, conventionality, conformity, education, knowledge, beliefs".split(', '),
    "The Lovers": "love, unions, partnerships, relationships, choices, romance, balance, unity".split(', '),
    "The Chariot": "success, ambition, determination, willpower, control, self-discipline, focus".split(', '),
    "Strength": "courage, bravery, confidence, compassion, self-confidence, inner power".split(', '),
    "The Hermit": "self-reflection, introspection, contemplation, withdrawal, solitude, search for self".split(', '),
    "The Wheel of Fortune": "change, cycles, fate, decisive moments, luck, fortune, unexpected events".split(', '),
    "Justice": "justice, karma, consequence, accountability, law, truth, honesty, integrity, cause and effect".split(', '),
    "The Hanged Man": "sacrifice, waiting, uncertainty, lack of direction, perspective, contemplation".split(', '),
    "Death": "transformation, endings, change, transition, letting go, release".split(', '),
    "Temperance": "balance, peace, patience, moderation, calm, tranquillity, harmony, serenity".split(', '),
    "The Devil": "oppression, addiction, obsession, dependency, excess, powerlessness, limitations".split(', '),
    "The Tower": "disaster, destruction, upheaval, trauma, sudden change, chaos".split(', '),
    "The Star": "hope, inspiration, positivity, faith, renewal, healing, rejuvenation".split(', '),
    "The Moon": "illusion, intuition, uncertainty, confusion, complexity, secrets, unconscious".split(', '),
    "The Sun": "happiness, success, optimism, vitality, joy, confidence, happiness, truth".split(', '),
    "Judgement": "self-evaluation, awakening, renewal, purpose, reflection, reckoning".split(', '),
    "The World": "completion, achievement, fulfilment, sense of belonging, wholeness, harmony".split(', '),
    }

dictionary_of_lists_major_arcana_to_negative_attributes = {
    "The Fool": "reckless, careless, distracted, naive, foolish, gullible, stale, dull".split(', '),
    "The Magician": "manipulation, cunning, trickery, wasted talent, illusion, deception".split(', '),
    "The High Priestess": "repressed intuition, hidden motives, superficiality, confusion, cognitive dissonance".split(', '),
    "The Empress": "insecurity, overbearing, negligence, smothering, lack of growth, lack of progress".split(', '),
    "The Emperor": "tyrant, domineering, rigid, stubborn, lack of discipline, recklessness".split(', '),
    "The Hierophant": "rebellion, unconventionality, non-conformity, new methods, ignorance".split(', '),
    "The Lovers": "disharmony, imbalance, conflict, detachment, bad choices, indecision".split(', '),
    "The Chariot": "forceful, no direction, no control, powerless, aggression, obstacles".split(', '),
    "Strength": "self-doubt, weakness, low confidence, inadequacy, cowardice, forcefulness".split(', '),
    "The Hermit": "loneliness, isolation, recluse, being anti-social, rejection, returning to society".split(', '),
    "The Wheel of Fortune": "bad luck, lack of control, clinging to control, unwelcome changes, delays".split(', '),
    "Justice": "injustice, retribution, dishonesty, corruption, dishonesty, unfairness, avoiding accountability".split(', '),
    "The Hanged Man": "stalling, disinterest, stagnation, avoiding sacrifice, standstill, apathy".split(', '),
    "Death": "fear of change, repeating negative patterns, resisting change, stagnancy, decay".split(', '),
    "Temperance": "imbalance, excess, extremes, discord, recklessness, hastiness".split(', '),
    "The Devil": "independence, freedom, revelation, release, reclaiming power, reclaiming control".split(', '),
    "The Tower": "averting disaster, delaying the inevitable, resisting change".split(', '),
    "The Star": "hopelessness, despair, negativity, lack of faith, despondent".split(', '),
    "The Moon": "fear, deception, anxiety, misunderstanding, misinterpretation, clarity, understanding".split(', '),
    "The Sun": "blocked happiness, excessive enthusiasm, pessimism, unrealistic expectations, conceitedness".split(', '),
    "Judgement": "self-doubt, lack of self-awareness, failure to learn lessons, self-loathing".split(', '),
    "The World": "lack of closure, lack of achievement, feeling incomplete, emptiness".split(', '),
    }